import { Suspense } from 'react';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { Spin } from 'antd';
import { AntdRegistry } from '@ant-design/nextjs-registry';

import StoreProvider from './StoreProvider';
import LayoutState from '@/src/layout/LayoutState';

import './globals.scss';

const geistSans = localFont({
  src: '../src/assests/fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
});
const geistMono = localFont({
  src: '../src/assests/fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
});

export const metadata: Metadata = {
  title: 'Quản lý lớp học',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <AntdRegistry>
            <Suspense fallback={<Spin size="large" />}>
              <LayoutState>{children}</LayoutState>
            </Suspense>
          </AntdRegistry>
        </body>
      </html>
    </StoreProvider>
  );
}
