import { Metadata } from 'next';
import { PropsWithChildren } from 'react';

export const metadata: Metadata = {
  title: 'Đăng nhập',
  description: 'Generated by create next app'
};

function Layout(props: PropsWithChildren) {
  const { children } = props;
  return (
    <div className="flex justify-center items-center min-h-screen">
      {children}
    </div>
  );
}

export default Layout;
